name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project environment
        uses: ./.github/actions/setup

      - name: Run Linter
        run: pnpm run lint

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project environment
        uses: ./.github/actions/setup

      - name: Run Prettier
        run: npx prettier . --check

  type-check:
    name: Check type error
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project environment
        uses: ./.github/actions/setup

      - name: Run tsc
        run: npx tsb -b --noEmit
